### ISSUE TITLE
Server on Raspberry Pi 2 B _ App Support

### ISSUE THREAD

**Issue by Urvishic** [itead/IoTgo_Android_App#2]
Dear Team,

Need guidenace on App.
I have created internal server on Pi 2 . Now If I have to Build app for my internal IP : 10.0.0.1 : Where and What changes I have to Do?

Please Guide...

**Comment by humingchun** [comment]
Hi @Urvishic 

Please edit [settings.js](https://github.com/itead/IoTgo_Android_App/blob/master/www/services/settings.js), and change host from _172.16.7.188:3000_ to _10.0.0.1_ (add port if IoTgo is not running on 80).

**Comment by Urvishic** [comment]
Thank you ! @humingchun !

**Comment by Urvishic** [comment]
Okay ! Thanks! :+1:
